config/routes.rb
Rails.application.routes.draw do

  root 'tweets#dashboard'

  post 'tweets' => 'tweets#create', as: :tweets

  get '/login' =>  'sessions#new', as: :login
  post 'auth' => 'sessions#create', as: :auth
  get '/logout' => 'sessions#destroy', as: :logout

  get '/users/:id' => 'users#show', as: :user
  get '/signup' => 'users#new', as: :signup
  post '/users' => 'users#create', as: :users
  delete '/users/:id' => 'users#destroy', as: :delete_user

  get '/follow/:id' => 'users#follow', as: :follow
  get '/unfollow/:id' => 'users#unfollow', as: :unfollow

  post 'posts' => 'posts#create', as: :posts
  delete 'tweets/:id' => 'tweets#delete', as: :delete_tweet

  resources :users

end

app/models/follow.rb
class Follow < ActiveRecord::Base

  extend ActsAsFollower::FollowerLib
  extend ActsAsFollower::FollowScopes

  # NOTE: Follows belong to the "followable" interface, and also to followers
  belongs_to :followable, :polymorphic => true
  belongs_to :follower,   :polymorphic => true

  def block!
    self.update_attribute(:blocked, true)
  end

end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to :user
  validates :content, presence: true, length: { maximum: 140}
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :tweets
  has_secure_password
  acts_as_followable
  acts_as_follower

  validates  :username, presence: true, length:{maximum: 50},  uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 8}
  validates  :password_confirmation, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionHelper


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def dashboard
    
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
      @tweet = Tweet.new
      @users = User.all
      @tweets = Tweet.all
                    .order("created_at desc")
                    .page(1)
                    .per(5)
  end

  def create
    @tweets = Tweet.all

    username = params[:username]
    password = params[:password]

    user = User.find_by username: username
    if (user) && (user.authenticate password)
      session[:user_id] = user.id
      redirect_to root_path
    else
      flash.now[:danger] = "Try again. Invalid email/password combination"
      render :new
    end
  end

  def destroy
    session.delete :user_id
    redirect_to root_path
  end

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

  before_action do
    @tweets = Tweet.all
                   .order("created_at desc")
                   .page(params[:page])

    @current_user = User.find_by id: session[:user_id]
      if @current_user.nil?
        redirect_to login_path
      end
    end

  def index
  end


  def new
    @tweet = Tweet.new
  end


  def dashboard
    @tweet = Tweet.new
    @users = User.all

    unless @current_user.nil?
      followers_id = @current_user.following_users.pluck(:id)
      tweets_ids = followers_id << @current_user.id
    end

    @tweets = Tweet.where(user_id: tweets_ids).order("created_at desc").page(params[:page]).per(5)
    @users = User.all
                .reject{|user| @current_user.following? user}
                .reject{|user| @current_user == user}
  end


  def create
  @tweet = Tweet.new params.require(:tweet).permit (:content)
  @tweet.user_id = @current_user.id
    if @tweet.save
      redirect_to root_path
    else
      render :new
    end
  end

  def follow
    user = User.find(params[:id])
    @current_user.follow(user)
    redirect_to root_path, notice: "You are now following " "#{user.username}"
  end


  def unfollow
      user = User.find(params[:id])
      @current_user.stop_following(user)
      redirect_to root_path, notice: "You just unfollowed " "#{user.username}"
  end


  def delete
    @tweet = Tweet.find params[:id]
    @tweet.destroy
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

# before_action
#   :showing_followers


  before_action :auth_user!, except: [:new, :create]

  def auth_user!
    @user_id = session[:user_id]
    @current_user = User.find_by id: @user_id

     if @current_user.nil?
        redirect_to login_path
    else
      user = User.find(params[:id])
      @current_user.follow(@current_user)
    end
  end


  def new
    @user = User.new
  end


  def index
    @users = User.all
  end


  def show
    @user = User.find(params[:id])
    @tweets = @user.tweets
    followers_id = @current_user.following_users.pluck(:id)
    id_of_tweets = followers_id << @current_user.id
    @tweets = Tweet.where(user_id: id_of_tweets).order("created_at desc").page(params[:page])
    @users = User.all
                .reject{|user| @current_user.following? user}
                .reject{|user| @current_user == user}
  end


  def create
    @user = User.new params.require(:user).permit(:username, :password, :password_confirmation, :id)
    if @user.save
        flash[:success] = "Welcome to Twitta!"
        session[:user_id] = @user.id
        redirect_to root_path
      else
        render :new
      end
  end


  def follow
    user = User.find(params[:id])
    @current_user.follow(user)
    redirect_to root_path, notice: "You are now following " "#{user.username}"
  end


  def unfollow
      user = User.find(params[:id])
      @current_user.stop_following(user)
      redirect_to root_path, notice: "You just unfollowed " "#{user.username}"
  end


  def destroy
    @current_user = User.find(params[:id])
    @current_user.destroy
    redirect_to login_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/session_helper.rb
module SessionHelper

  def logged_in?
    !@current_user.nil?
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Twitta</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href='https://fonts.googleapis.com/css?family=Clicker+Script' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=EB+Garamond' rel='stylesheet' type='text/css'>
</head>

<body>
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>

  <nav class="navbar">
    <div class="nav">
      <div id="top"> <h1> Twitta!!! </h1> </div>
      <% if logged_in? %>
        <%= link_to "Log Out", logout_path %>
      <% end%>
    </div>
  </nav>

  <%= yield %>

</body>
</html>

app/views/tweets/dashboard.html.erb
<div class="row">

<div class="col-md-3">
</div>


<div class="col-md-6">
<div class ="tweets">

    <h1> Hello <%= @current_user.username.upcase %>!!! </h1>
    <h3> Say something... </h3>
    <%= simple_form_for @tweet do |f| %>
      <%= f.input :content, as: :text, label: false %>
      <%= f.submit "Tweet It", class: 'btn btn-primary' %>
      <br>
      <% end %>
      <br>

      <h4> You have <%= pluralize @tweets.total_count, "Tweets" %> </h4>

      <div class:"btn">
        <%= paginate @tweets %>
      </div>

      <% @tweets.each do |tweet| %>
            <div class="panel panel-default">
            <div class="panel-body">
              <h5><strong><%= tweet.content %></strong></h5>
              <h6><em> Posted by: <%= tweet.user.username %></em></h6>
              <h6>Posted: <%= distance_of_time_in_words_to_now tweet.created_at %> </h6>
            </div>
            </div>
          <% end %>
      <div class:"btn">
        <%= paginate @tweets %>
      </div>

</div>
</div>

<div class="col-md-3">

  <h3 style="text-align:center">Following:</h3>
    <ul class="list-group">
      <% @current_user.all_following.each do |user| %>
        <li class="list-group-item">
          <%= link_to "#{user.username}", unfollow_path(id: user.id) %>
        </li>
      <% end %>
    </ul>

  <h3 style="text-align:center">Other People:</h3>
    <ul class="list-group">
      <% @users.each do |user| %>
        <li class="list-group-item">
         <%= link_to "#{user.username}", follow_path(id: user.id) %>
        </li>
     <% end %>
   </ul>

</div>

app/views/users/new.html.erb
<div class="col-sm-6 .col-md-2" id="new" >

  <h1>Sign up.</h1>
  <h4 style="text-align:center"> Do it. </h4>

    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <div class="label">
            <%= simple_form_for @user do |f| %>
            <%= f.input :username%>
            <%= f.input :password %>
            <strong> *Confirm Password </strong>
            <%= f.input :password_confirmation, label: false %>
              <%= f.button :submit %>
            <%end%>
          </div>
          <br>
          <br>
      </div>
</div>
</div>

app/views/users/show.html.erb
<% provide(:content, @current_user.username) %>

<div class="row">

  <section class="user_info">
    <h1>
      Welcome <%= @current_user.username.capitalize %>,</br>
      You are following <%= pluralize @current_user.follow_count, "people" %> </h1>
  </section>
</div>

<div class="row">

  <div class="col-md-3">
  </div>


  <div class="col-md-6">
    <h3> Recent Posts </h3>
    <% @tweets.each do |tweet| %>
      <div class="panel panel-default">
      <div class="panel-body">
        <h5><strong><%= tweet.content %></strong></h5>
        <br>
        <em>Posted by: <%= tweet.user.username %></em>
        <br>
        Posted: <%= distance_of_time_in_words_to_now tweet.created_at %>
        <br>
      </div>
      </div>
    <% end %>
    <br clear="all"/>
    <div class:"btn">
      <%= paginate @tweets %>
    </div>
  </div>


  <div class="col-md-3 left">
    <h3 style="text-align:center">Following:</h3>
      <ul class="list-group">
        <% @current_user.all_following.each do |user| %>
          <li class="list-group-item">
          <%= link_to "#{user.username}", unfollow_path(id: user.id) %>
          </li>
        <%end%>
      </ul>

    <h3 style="text-align:center">Other People:</h3>
      <ul class="list-group">
        <% @users.each do |user| %>
          <li class="list-group-item">
           <%= link_to "#{user.username}", follow_path(id: user.id) %>
          </li>
       <%end%>
     </ul>
  </div>

</div>